//constantes 
export const GET_CHARACTERS_REQUEST = 'GET_CHARACTERS_REQUEST'
export const GET_CHARACTERS_REQUEST_ERROR = 'GET_CHARACTERS_REQUEST_ERROR'
 
export const GET_CHARACTER_ID_REQUEST = 'GET_CHARACTER_ID_REQUEST'
export const GET_CHARACTER_ID_ERROR = 'GET_CHARACTER_ID_ERROR'

export const GET_QUERY = 'GET_QUERY'

export const GET_OPEN_MODAL = 'GET_OPEN_MODAL'